import Groq from 'groq-sdk';
import nodemailer from 'nodemailer';
import { v4 as uuidv4 } from 'uuid';

// Groq Client (OpenAI-compatible API)
const groq = new Groq({
  apiKey: process.env.GROQ_API_KEY || ''
});

// Email Transporter
const emailTransporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER || 'your-email@gmail.com',
    pass: process.env.EMAIL_PASSWORD || 'your-password'
  }
});

// Alternative: Use environment-based SMTP
if (process.env.SMTP_HOST) {
  nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port: parseInt(process.env.SMTP_PORT || '587'),
    secure: process.env.SMTP_SECURE === 'true',
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASSWORD
    }
  });
}

/**
 * Run real AI simulation using Groq (Llama 3.3 70B)
 */
export async function runAISimulation(
  agentRole: string,
  testData: any[],
  tools: string[]
) {
  try {
    const prompt = `You are a ${agentRole} AI agent. You have access to these tools: ${tools.join(', ')}.
    
Test Cases to evaluate:
${testData.map((t, i) => `${i + 1}. ${JSON.stringify(t)}`).join('\n')}

For each test case:
1. Provide your response
2. Rate your confidence (0-100)
3. Estimate cost based on tools used ($0.01-$1.00)
4. Estimate latency (100-5000ms)

Format your response as JSON array with: response, confidence, cost, latency, success`;

    const response = await groq.chat.completions.create({
      model: 'llama-3.3-70b-versatile',
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.7,
      max_tokens: 2000
    });

    const content = response.choices[0].message.content || '[]';
    const results = JSON.parse(content);

    // Calculate aggregate metrics
    const accuracy = results.reduce((sum: number, r: any) => sum + (r.confidence || 0), 0) / results.length;
    const cost = results.reduce((sum: number, r: any) => sum + (r.cost || 0.01), 0);
    const latency = Math.max(...results.map((r: any) => r.latency || 1000));
    const failureRate = results.filter((r: any) => !r.success).length / results.length * 100;

    return {
      accuracy: Math.round(accuracy * 100) / 100,
      cost: Math.round(cost * 100) / 100,
      latency,
      failure_rate: Math.round(failureRate * 100) / 100,
      results
    };
  } catch (err) {
    console.error('AI Simulation error:', err);
    throw new Error('Failed to run AI simulation');
  }
}

/**
 * Run agent task using Groq LLM
 */
export async function runAgentTask(
  agentRole: string,
  input: string,
  tools: string[]
) {
  try {
    const prompt = `You are a ${agentRole} AI agent with these tools: ${tools.join(', ')}.
    
Task: ${input}

Respond with:
1. Your action/response
2. Confidence (0-100)
3. Estimated cost
4. Success status

Keep response concise and actionable.`;

    const response = await groq.chat.completions.create({
      model: 'llama-3.3-70b-versatile',
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.5,
      max_tokens: 500
    });

    const output = response.choices[0].message.content || '';

    return {
      output,
      task_id: uuidv4(),
      model: 'llama-3.3-70b-versatile',
      tokens_used: response.usage?.total_tokens || 0
    };
  } catch (err) {
    console.error('Agent task error:', err);
    throw new Error('Failed to run agent task');
  }
}

/**
 * Send real email via deployment
 */
export async function sendEmailDeployment(
  to: string,
  subject: string,
  agentOutput: string
) {
  try {
    const mailOptions = {
      from: process.env.EMAIL_USER || 'noreply@workplace-ai.com',
      to,
      subject: `[Workplace-AI] ${subject}`,
      html: `
        <h2>${subject}</h2>
        <p>Your AI agent has completed a task:</p>
        <div style="background: #f5f5f5; padding: 15px; border-radius: 5px;">
          ${agentOutput}
        </div>
        <p style="font-size: 12px; color: #666;">
          This email was generated by Workplace-AI agents.
        </p>
      `
    };

    const info = await emailTransporter.sendMail(mailOptions);
    return {
      success: true,
      messageId: info.messageId,
      timestamp: new Date()
    };
  } catch (err) {
    console.error('Email deployment error:', err);
    throw new Error('Failed to send email');
  }
}

/**
 * Parse agent response
 */
export function parseAgentResponse(output: string) {
  try {
    // Try to parse as JSON first
    return JSON.parse(output);
  } catch {
    // Otherwise return as structured text
    return {
      text: output,
      confidence: 75,
      success: true
    };
  }
}

export { groq, emailTransporter };

